### PR TITLE
`ISingleAxisSubsystem` fixes

### LINKED ISSUE #18: Use Rev's new PID system

### LINKED ISSUE #19: Fix `SetEncoderConversionFactor()` and `SetAbsoluteEncoderConversionFactor()`
`SetPositionConversionFactor()` doesn't exist anymore

### PR DESCRIPTION
**Pull request by 5690Programmers**
# Description of pull request

This PR fixed ISingleAxisSubsystem using the new rev API

Closes #18 
Closes #19 

- [ ] Compiles
- [ ] Unit tests pass
- [ ] Tested on the robot
- [ ] Reviewed by another member

### CODE REVIEW

File: lib/include/subzero/autonomous/AutoFactory.h [hunk 1]
```diff
@@ -34,31 +34,9 @@ template <typename T> class AutoFactory {
...
-  frc2::CommandPtr PathPlannerPathFromName(const std::string autoName) {
-    if (!AutoFileExists(autoName)) {
-      ConsoleWriter.logError("Auto Factory",
-                             "AUTO '%s' DOES NOT EXIST HELP US EVAN",
-                             autoName.c_str());
-      return EmptyCommand().ToPtr();
-    }
-    return pathplanner::PathPlannerAuto(autoName).ToPtr();
-  }
+  frc2::CommandPtr PathPlannerPathFromName(const std::string autoName);
```
Comment (nobody5050) [inline lib/include/subzero/autonomous/AutoFactory.h:39]: Make sure if you're removing the header only implementation that you have a cpp somewhere so you don't get a linking error

File: lib/include/subzero/motor/PidMotorController.h [hunk 2]
```diff
@@ -109,8 +117,14 @@ class PidMotorController : public IPidMotorController {
    *
    * @param factor
    */
+  // TODO: find missing SetPositionConversionFactor() method
```
Comment (nobody5050) [inline lib/include/subzero/motor/PidMotorController.h]: You probably need to do this before you can use iSingleAxis for an elevator

File: lib/include/subzero/autonomous/AutoFactory.h (hunk 1 above)
Comment (nobody5050) [inline lib/include/subzero/autonomous/AutoFactory.h:39]: Make sure if you're removing the header only implementation that you have a cpp somewhere so you don't get a linking error

**Review by nobody5050 — CHANGES_REQUESTED** [review]
Looks good, solve the `TODO` commentd before merging

File: lib/include/subzero/autonomous/AutoFactory.h (hunk 1 above)
Comment (5690Programmers) [reply lib/include/subzero/autonomous/AutoFactory.h:39]: We do have the C++ implementation; something must have changed with the build system because when we had two implementations it gave be redefinition errors

File: lib/include/subzero/motor/PidMotorController.h (hunk 2 above)
Comment (5690Programmers) [reply lib/include/subzero/motor/PidMotorController.h]: Oop we already solved that just forgot to remove the TODO

**Review by CanyonJ — APPROVED** [review]

**Review by nobody5050 — APPROVED** [review]
